gateways:
    local:
        connection:
            type: duckdb
            database: db.db

default_gateway: local

model_defaults:
    dialect: duckdb

cicd_bot:
    type: github
    merge_method: squash
    enable_deploy_command: true
